version: '3.8'

services:
  agency-planner:
    container_name: agency-planner
    image: raphauy/agency-planner:latest
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8056:3000
    networks:
      - rc-network

networks:
  rc-network:
    external:
      name: rc-network
